### ISSUE TITLE
Skid Drive

### ISSUE THREAD

**Issue by dimikout3** [jazzl0ver/ardupilot-rover-l298n#1]
Great Work! I am working on a similar project, but I want to use skid driving. I have tried the configuration depicted here:

https://diydrones.com/profiles/blogs/ardurover-skid-steering

In which the ENA&IN2 and ENB&IN3 are wired together, but the motors are not spinning. I believe that something similar to what you presented is the answer. Could you provide me with any information?

Thank in advance!

**Comment by jazzl0ver** [comment]
I guess I faced similar issue and the solution was to send signals to ENx and INx separately. That's why I needed to use LUA scripting and all other stuff.
You'll just need to use my wiring layout and update the script to change the logic for skid steering

**Comment by dimikout3** [comment]
I came to the same conclusion. I will use your lua script as a base.

Another question is how the PWM controls the speed in your case. I have a 12V constant supply in INx and then connect the PWM (from the pixhawk) to the ENx. The rover just spins the DC motor at the same speed regardless of the PWM (1100ms - 1900ms, trim 1100ms), the pwm is controlled via rc, but I have also tested from the "test motor" function via the Mission Planner.

@jazzl0ver did you manage to control the speed of your rover smoothly?

Once again, thanks for your help!

**Comment by jazzl0ver** [comment]
You shouldn't supply 12V to INx pins. Those are powered from AUX outputs of Pixhawk, which provides around 5V (logical 1 or 0). You supply power via Vcc pin of the L298N board. Please, read carefully my instructions.
The speed control was not great, but it was smooth enough for this type of the speed controller and motors, I guess.

**Comment by dimikout3** [comment]
Great! Thanks for the help once more. I will come back when I have some news!

**Comment by dimikout3** [comment]
Hi again, I implemented exactly what you did @jazzl0ver, but it did not work, I am starting to think that the L298n I have is broken. Could you share a photo/sketch of the wiring you implemented between the L298n and the pixhawk?

**Comment by jazzl0ver** [comment]
@dimikout3 I don't have the photo or sketch. I believe the "Wiring" table I created is much more informative. Just connect signal pins as outlined in the table and you should be good. Make sure you followed the prerequisites like firmware and Ardupilot versions - they matter.

**Comment by giangthewalkingman** [comment]
I wired like @jazzl0ver  and the steering function doesn't work, however, the throttle works quite okay. I still don't understand why in this case. Besides, I want to develop skid-steering code from the wiring diagram u provided from Lua scripts. Have u met the similar problem @jazzl0ver or your car worked properly?
Btw, thanks so much because you help me know that Lua script is very useful in integrating with DC motor drivers!

**Comment by giangthewalkingman** [comment]
hey @dimikout3 I met the similar problem like you. Have you solved that problem =)))?

**Comment by jazzl0ver** [comment]
hi @giangthewalkingman. Thanks for your credits, it's a pleasure for me to know that my efforts were not a waste of time!

Answering your question - I faced a lot of problems while trying to make things work correctly. Fortunately, it's not a rocket science and all of them is mostly a bad wiring (bad contacts). What I would do in your case:
1. Swap the throttling and steering motor drivers. This will tell you if the driver itself works
2. Use multimeter and make sure you got a correct voltage from the Pixhawk controller output signal pin when you change the steering stick position on the remote control
3. Check the LUA script output in Mission Planner

HTH

**Comment by Pierre-Luca** [comment]
Hey, I am quite new into pixhawk stuff and I have problems just at the beginning. My first goal is to run a normal brushed motor with my radio. Doesn't matter how. I followed the construction of @jazzl0ver but had problems with it. Can sb help?

**Comment by jazzl0ver** [comment]
@Pierre-Luca, what exactly do you need help with?

**Comment by Pierre-Luca** [comment]
@jazzl0ver i have a 11.1V battery connected to the pixhawk. Also a L298N motordriver. Everything is lighting up, so it has power. But no matter how, the connected motor won't spin. Not with the motortest in mission planner and nor with the radio. Can you help with the connection? I have an ENA pin, and to IN pins from the driver. Where do I have to put them and what do I have to tell the mission planner?

**Comment by jazzl0ver** [comment]
@Pierre-Luca you connect the ENA pin of the driver to the PWM1 pin of the PixHawk, IN1 of the driver goes to the AUX3 of the PixHawk. Check the voltages between pins (signal and ground, power and ground) when doing the motortest.
